export const company = {
  name: "MySarah Modern Tech Private Limited",
  shortName: "MySarah Modern Tech",
  city: "Assam",
  country: "India",
  phone: "+91 9365357806",
  email: "mysarahmoderntechpvtltd2025@gmail.com",
  whatsappNumber: "919365357806",
  address: "Sivasagar, Assam, India",
  socialProfiles: {
    instagram: "https://www.instagram.com/mysarah_modern_tech_pvt.ltd?igsh=YzZvaXAzdGg4enh1",
    facebook: "https://www.facebook.com/mysarahmoderntech",
    linkedin: "https://www.linkedin.com/company/mysarah-modern-tech",
  },
};

const solarKeywordSeeds = [
  "solar installation near me",
  "rooftop solar installation india",
  "solar panel installation company",
  "best solar company in india",
  "solar system installation services",
  "solar rooftop installer near me",
  "residential solar installation india",
  "commercial solar installation india",
  "solar panel dealer near me",
  "solar installation service provider",
  "solar company near me india",
  "solar epc company india",
  "solar turnkey project company",
  "solar system for home india",
  "solar power system installation",
  "solar panel cost in india",
  "rooftop solar price india",
  "solar system price for home",
  "1kw solar panel price india",
  "2kw solar system price india",
  "3kw solar panel cost india",
  "5kw solar system price india",
  "10kw solar system price india",
  "solar installation cost per kw india",
  "rooftop solar subsidy price india",
  "solar panel price with subsidy india",
  "solar battery price india",
  "inverter solar cost india",
  "solar setup cost for house",
  "solar electricity cost india",
  "solar subsidy india 2026",
  "rooftop solar subsidy india",
  "pm solar yojana details",
  "solar subsidy for home india",
  "how to apply solar subsidy india",
  "solar scheme india rooftop",
  "mnre solar subsidy india",
  "government solar scheme for home",
  "solar subsidy eligibility india",
  "free solar scheme india",
  "solar installation delhi",
  "solar company mumbai",
  "solar panel bangalore",
  "solar rooftop chennai",
  "solar installation hyderabad",
  "solar company pune",
  "solar system kolkata",
  "solar installer ahmedabad",
  "solar company jaipur",
  "solar installation lucknow",
  "solar system chandigarh",
  "solar rooftop bhopal",
  "solar installation patna",
  "solar company indore",
  "solar system nagpur",
  "solar installation surat",
  "solar company coimbatore",
  "solar system kochi",
  "solar rooftop guwahati",
  "solar company bhubaneswar",
  "solar installation assam",
  "solar company assam",
  "solar panel sivasagar",
  "solar subsidy assam",
  "solar for factory india",
  "industrial solar installation india",
  "solar for business india",
  "commercial rooftop solar india",
  "solar plant installation company",
  "solar epc contractor india",
  "solar power for warehouse india",
  "solar energy for industries india",
  "solar solution for offices",
  "solar power system for hotels",
  "solar for hospitals india",
  "solar for schools india",
  "electricity bill too high solution india",
  "how to reduce electricity bill india",
  "alternative to electricity india",
  "solar vs electricity cost india",
  "how to save electricity at home india",
  "best energy solution for home india",
  "power backup solution india",
  "inverter vs solar which is better",
  "solar worth it in india",
  "solar benefits india",
  "best solar panel brand india",
  "tata solar vs adani solar",
  "solar vs generator cost",
  "solar vs inverter india",
  "rooftop solar vs normal solar",
  "on grid vs off grid solar india",
  "hybrid solar system india",
  "which solar system is best for home",
  "how much solar needed for house",
  "best solar system for 2bhk house india",
  "solar system for small house india",
  "rooftop solar for independent house",
  "solar panel for village house india",
  "solar setup for home with battery",
  "solar system for 24 hour electricity",
  "solar for areas with power cut",
  "solar installation process india",
  "how long does solar last india",
  "maintenance of solar panels india",
  "solar installation india",
  "solar price india",
  "solar subsidy india",
  "best rooftop solar company india",
  "home solar panel installation",
  "office rooftop solar installation",
  "factory solar project india",
  "solar amc services india",
  "net metering solar india",
  "on grid solar installation india",
  "off grid solar installation india",
  "hybrid solar installation india",
  "solar project consultation india",
  "solar installer for home",
  "solar installer for business",
  "solar financing india",
  "solar loan india",
  "solar emi plans india",
  "solar plant for apartment india",
  "solar for bungalow india",
  "solar for farmhouse india",
  "solar for shop india",
  "solar panel cleaning service india",
  "solar inverter installation india",
  "best solar installer guwahati",
  "rooftop solar guwahati",
  "solar panel installation assam",
  "mysarah modern tech",
  "mysarah solar",
  "mysarah modern tech solar installation",
  "solar company india",
  "rooftop solar installation India",
  "best solar company in India",
  "solar company near me India",
  "solar EPC company India",
  "solar system for home India",
  "solar panel cost in India",
  "rooftop solar price India",
  "1kW solar panel price India",
  "2kW solar system price India",
  "3kW solar panel cost India",
  "5kW solar system price India",
  "10kW solar system price India",
  "solar installation cost per kW India",
  "inverter + solar cost India",
  "solar subsidy India 2026",
  "rooftop solar subsidy India",
  "PM solar yojana details",
  "MNRE solar subsidy India",
  "solar installation Delhi",
  "solar company Mumbai",
  "solar panel Bangalore",
  "solar rooftop Chennai",
  "solar installation Hyderabad",
  "solar company Pune",
  "solar system Kolkata",
  "solar installer Ahmedabad",
  "solar company Jaipur",
  "solar installation Lucknow",
  "solar system Chandigarh",
  "solar rooftop Bhopal",
  "solar installation Patna",
  "solar company Indore",
  "solar system Nagpur",
  "solar installation Surat",
  "solar company Coimbatore",
  "solar system Kochi",
  "solar rooftop Guwahati",
  "solar company Bhubaneswar",
  "solar for factory India",
  "industrial solar installation India",
  "commercial rooftop solar India",
  "solar EPC contractor India",
  "solar power for warehouse India",
  "solar for hospitals India",
  "solar for schools India",
  "solar vs electricity cost India",
  "solar worth it in India",
  "solar vs inverter India",
  "on-grid vs off-grid solar India",
  "best solar system for 2BHK house India",
  "solar system for small house India",
  "solar panel for village house India",
  "solar installation process India",
  "how long does solar last India",
  "maintenance of solar panels India",
];

const mysarahKeywordSeeds = [
  "mysarah",
  "mysarah modern tech",
  "mysarah modern tech private limited",
  "mysarah tech",
  "my sarah",
  "my sarah solar",
  "mysarah solar",
  "mysarah solar installation",
  "mysarah solar company",
  "mysarah rooftop solar",
  "mysarah solar subsidy",
  "mysarah solar price",
  "mysarah solar panel installation",
  "mysarah commercial solar",
  "mysarah epc",
  "mysarah assam",
  "mysarah sivasagar",
  "mysarah contact",
  "mysarah whatsapp",
  "mysarah modern tech solar installation",
];

function toTitleCase(value: string) {
  return value
    .split(" ")
    .map((part) => (part ? `${part.charAt(0).toUpperCase()}${part.slice(1)}` : part))
    .join(" ");
}

const solarKeywordsExpanded = Array.from(
  new Set(
    [...solarKeywordSeeds, ...mysarahKeywordSeeds].flatMap((keyword) => [
      keyword,
      keyword.toLowerCase(),
      toTitleCase(keyword),
      keyword.toUpperCase(),
    ]),
  ),
);

export const seo = {
  title: "MySarah Modern Tech Pvt.Limited-MultiSector Company",
  description:
    "Mysarah Modern Tech delivers rooftop solar installation, commercial solar EPC, subsidy guidance, and end-to-end solar project execution across India.",
  keywords: solarKeywordsExpanded,
};
